
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: gift registry > supporting infrastructure

Parameters:
  FileUrlDuration:
    Type: String
    Default: 60s
    Description: Duration that a file URL is valid for

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "gift-registry-images-${AWS::AccountId}"
      VersioningConfiguration: 
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  BucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/s3/images/name'
      Type: String
      Value: !Ref ImageBucket
      Description: Name of the S3 bucket to store gift registry images in

  BucketArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/s3/images/arn'
      Type: String
      Value: !GetAtt ImageBucket.Arn
      Description: ARN of the S3 bucket to store gift registry images in

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "gift-registry-website-${AWS::AccountId}"
      VersioningConfiguration: 
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  WebsiteBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/s3/website/name'
      Type: String
      Value: !Ref WebsiteBucket
      Description: Name of the S3 bucket to store gift registry website in

  WebsiteBucketArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/s3/website/arn'
      Type: String
      Value: !GetAtt WebsiteBucket.Arn
      Description: ARN of the S3 bucket to store gift registry website in

  UrlLifespanParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/s3/images/url-lifespan'
      Type: String
      Value: !Ref FileUrlDuration
      Description: Lifepsan of the presigned URLs generated for images in the S3 bucket

  GiftDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: gift-registry-gifts
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: listId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: listIdIndex
          KeySchema:
            - AttributeName: listId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  GiftTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/ddb/gifts/name'
      Type: String
      Value: !Ref GiftDynamoDb
      Description: Name of the DynamoDB table to store gifts in

  GiftTableListIndexNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/ddb/gifts/list-index/name'
      Type: String
      Value: listIdIndex
      Description: Name of the List index for the DynamoDB table to store gifts in

  GiftTableArnParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: '/gift-registry/ddb/gifts/arn'
        Type: String
        Value: !GetAtt GiftDynamoDb.Arn
        Description: Arn of the DynamoDB table to store gifts in

  ListDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: gift-registry-lists
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: sharingId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: userIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: sharingIdIndex
          KeySchema:
            - AttributeName: sharingId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  ListsTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/ddb/lists/name'
      Type: String
      Value: !Ref ListDynamoDb
      Description: Name of the DynamoDB table to store lists in

  ListTableUserIndexNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/ddb/lists/user-index/name'
      Type: String
      Value: userIdIndex
      Description: Name of the User index for the DynamoDB table to store lists in

  ListTableSharingIdIndexNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/ddb/lists/sharing-id-index/name'
      Type: String
      Value: sharingIdIndex
      Description: Name of the Sharing id index for the DynamoDB table to store lists in

  ListsTableArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/ddb/lists/arn'
      Type: String
      Value: !GetAtt ListDynamoDb.Arn
      Description: Arn of the DynamoDB table to store lists in

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: gift-registry-user-pool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 10
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          PasswordHistorySize: 5
      MfaConfiguration: "OFF"
      UserPoolTier: ESSENTIALS

  CognitoUserPoolParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/cognito/user-pool/id'
      Type: String
      Value: !Ref CognitoUserPool
      Description: ID of the Cognito user pool

  CognitoUserPoolArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/cognito/user-pool/arn'
      Type: String
      Value: !GetAtt CognitoUserPool.Arn
      Description: Arn of the Cognito user pool

  CognitoUserPoolUrlParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/gift-registry/cognito/user-pool/url'
      Type: String
      Value: !GetAtt CognitoUserPool.ProviderURL
      Description: Url of the Cognito user pool